name: halo2-wasm Tests

on:
   push: 
     paths:
       - "halo2-wasm/**"

defaults:
  run:
    working-directory: halo2-wasm

jobs:
  halo2-wasm-tests:
    runs-on: ubuntu-latest-64core-256ram
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          rustup toolchain install nightly-2023-08-12-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-2023-08-12-x86_64-unknown-linux-gnu
          cargo build --target=x86_64-unknown-linux-gnu --verbose
      - name: Test
        run: cargo test --target=x86_64-unknown-linux-gnu